apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
spec:
  type: ClusterIP
  selector:
    app: kafka-broker
  ports:
    - name: plaintext
      port: 29092
      targetPort: 29092
    - name: controller
      port: 29093
      targetPort: 29093
    - name: plaintext-host
      port: 9092
      targetPort: 9092